version: 2

#  Copyright (C) 2018-2019 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

jobs:
  build:
    docker:
      - image: usdotfhwastol/carma-base:2.8.2
        user: carma
        environment:
          TERM: xterm
    working_directory: "/opt/carma/"
    steps:
      - run:
          name: Create src folder
          command: |
            mkdir src
            cd src
            mkdir CARMAPlatform
            mkdir CARMAMsgs
      - checkout:
          path: src/CARMAPlatform
      - run: 
          name: Pull CARMAMsgs
          command: |
            source /opt/ros/kinetic/setup.bash
            git clone -b develop --depth 1 git@github.com:usdot-fhwa-stol/CARMAMsgs.git src/CARMAMsgs
      - run:
          name: Build CARMA
          command: |
            source /opt/ros/kinetic/setup.bash
            catkin_make install
      - run:
          name: Run C++ Tests
          command: |
            source /opt/ros/kinetic/setup.bash
            source /opt/carma/devel/setup.bash
            catkin_make run_tests
      - run:
          name: Run Java Tests
          command: |
            source /opt/ros/kinetic/setup.bash
            source /opt/carma/devel/setup.bash
            cd src/CARMAPlatform/carmajava/
            ./gradlew testReport --info
      - run:
          name: Save Java Test results
          command: |
            mkdir -p ~/junit/ 
            sudo mkdir -p /reports/tests
            sudo mv src/CARMAPlatform/carmajava/build/reports/allTests/* /reports/tests/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: /reports
